package com.med.qa.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;

import java.util.List;

/**
 * SpringDoc OpenAPI configuration (D26).
 *
 * <p>Builds the document metadata, the API-key security scheme that matches the
 * {@code ApiKeyAuthFilter}, and three controller groups (chat / session / rag) for Swagger UI. The
 * configuration relies entirely on the official springdoc / swagger-models API: no HTML, no hand-rolled
 * doc scaffolding, and no extra middleware. The document itself is generated by SpringDoc from the
 * existing controllers and DTOs at runtime.</p>
 */
@Configuration
@EnableConfigurationProperties(MedOpenApiProperties.class)
public class OpenApiConfig {

    /** Stable identifier of the API-key security scheme referenced by every operation. */
    public static final String API_KEY_SCHEME = "apiKeyAuth";

    /**
     * Builds the root OpenAPI document: title/version/description, optional contact and license, the
     * API-key security scheme, and a global security requirement so Swagger UI offers an "Authorize"
     * button wired to the exact header the server enforces.
     *
     * @param props the openapi configuration, must not be {@code null}
     * @return the configured {@link OpenAPI}, never {@code null}
     */
    @Bean
    @Primary
    public OpenAPI medOpenApi(MedOpenApiProperties props) {
        Info info = new Info()
                .title(props.getTitle())
                .version(props.getVersion())
                .description(props.getDescription());
        applyContact(info, props);
        applyLicense(info, props);

        Components components = new Components().addSecuritySchemes(API_KEY_SCHEME,
                new SecurityScheme()
                        .type(SecurityScheme.Type.APIKEY)
                        .in(SecurityScheme.In.HEADER)
                        .name(props.getApiKeyHeader())
                        .description("Opaque API key issued per principal; send it in the "
                                + props.getApiKeyHeader() + " request header."));

        return new OpenAPI()
                .info(info)
                .components(components)
                .addSecurityItem(new SecurityRequirement().addList(API_KEY_SCHEME));
    }

    private static void applyContact(Info info, MedOpenApiProperties props) {
        if (props.getContactName() == null && props.getContactEmail() == null
                && props.getContactUrl() == null) {
            return;
        }
        Contact contact = new Contact();
        if (props.getContactName() != null) {
            contact.setName(props.getContactName());
        }
        if (props.getContactEmail() != null) {
            contact.setEmail(props.getContactEmail());
        }
        if (props.getContactUrl() != null) {
            contact.setUrl(props.getContactUrl());
        }
        info.contact(contact);
    }

    private static void applyLicense(Info info, MedOpenApiProperties props) {
        if (props.getLicenseName() != null) {
            info.license(new License().name(props.getLicenseName()).url(props.getLicenseUrl()));
        }
    }

    /**
     * Swagger UI group for the streaming consultation endpoint.
     *
     * @param props the openapi configuration, must not be {@code null}
     * @return the chat group, never {@code null}
     */
    @Bean
    public GroupedOpenApi chatApiGroup(MedOpenApiProperties props) {
        return GroupedOpenApi.builder()
                .group("chat")
                .pathsToMatch(toArray(props.getChatGroupPaths()))
                .build();
    }

    /**
     * Swagger UI group for the session lifecycle endpoints.
     *
     * @param props the openapi configuration, must not be {@code null}
     * @return the session group, never {@code null}
     */
    @Bean
    public GroupedOpenApi sessionApiGroup(MedOpenApiProperties props) {
        return GroupedOpenApi.builder()
                .group("session")
                .pathsToMatch(toArray(props.getSessionGroupPaths()))
                .build();
    }

    /**
     * Swagger UI group for the RAG administration endpoints.
     *
     * @param props the openapi configuration, must not be {@code null}
     * @return the rag group, never {@code null}
     */
    @Bean
    public GroupedOpenApi ragApiGroup(MedOpenApiProperties props) {
        return GroupedOpenApi.builder()
                .group("rag")
                .pathsToMatch(toArray(props.getRagGroupPaths()))
                .build();
    }

    private static String[] toArray(List<String> paths) {
        return paths.toArray(new String[0]);
    }
}
